# lm_config.toml
[training.params]
epochs = 1
steps_per_epoch = 415000
batch_size = 16
alpha_max = 0.003
alpha_min = 0.0003
warmup_iter = 1000
theta = 10000
cooldown_iter = 373500
checkpoint_every = 5000
world_size = 1

[data.params]
path = "tiny_stories_train_token_out/"
tag = "shard_"
num_shards = 100

[model]
name = "cs336_basics.TransformerLM.TransformerLM"

[model.params]
vocab_size = 32000
context_length = 256
num_layers = 12
d_model = 768
num_heads = 12
d_ff = 2048
device = "cuda"

[optimizer]
name = "cs336_basics.adamW.AdamW"

[optimizer.params]
lr = 0.01
weight_decay = 0.01
betas = [0.9, 0.95]
eps = 1e-8

[validation.params]
# make sure validate every steps is N* checkpoint every steps
validate_every_steps = 500
vocab = "tokenizer/tiny_stories_train_vocab.pkl"
num_tries = 3

[validation.data]
path = "tiny_stories_valid_token_out"
tag = "shard_"
num_shards = 10
